### ISSUE TITLE
"race condition" for \r\n split on buffer length

### ISSUE THREAD

**Issue by wmertens** [jahewson/node-byline#23]
Pretty academic, but it seems to me that if you read a \r\n-encoded block which ends with \r (so the next block starts with \n), you will insert an extra empty line.
I suppose special-casing it by checking the last character of the buffer and the first one of the next one is the easiest fix but a little ugly.
Nicer would be to determine the line ending style from the first line ending and then split on only that, in which case there would not be a conflation of \r and \r\n endings. It might be faster, too.

**Comment by jahewson** [comment]
{quote}
If you read a \r\n-encoded block which ends with \r (so the next block starts with \n), you will insert an extra empty line.
{quote}

This is a legitimate bug. It's unlikely, as the only way to encounter it is to have a Windows-style line ending which falls exactly across two 65kb chunks. Other chunk sizes would increase the likelihood though.

{quote}
I suppose special-casing it by checking the last character of the buffer and the first one of the next one is the easiest fix but a little ugly.
{quote}

Not at all, in fact, it's what I'm going to do.

{quote}
Nicer would be to determine the line ending style from the first line ending and then split on only that, in which case there would not be a conflation of \r and \r\n endings. It might be faster, too.
{quote}

That would actually be a more brittle solution as it won't handle files which mix multiple styles (such files do unfortunately exist). It's also subject to the same problem, what happens when the first line ending in the file falls across two chunks?

**Comment by wmertens** [comment]
Cool!
