### ISSUE TITLE
Frequent pause/resume on large file causes data loss

### ISSUE THREAD

**Issue by virtualpatterns** [jahewson/node-byline#30]
When processing a large file (e.g. 20000 rows), with frequent pause/resume calls, lines are dropped from the end of the file (e.g. about 4000).

I'm using pause/resume to control the # of lines being processed.  Each line goes into a queue ... when the queue reaches a certain size the input is paused ... when it drops to 0 the input is resumed.  This works well when the # of pause/resume calls is very few.  As they get more frequent (i.e. I control the size of the queue) more data loss occurs.

A code sample (ugly) without the input file ...

```
var Asynchronous = require('async');
var ByLine = require('byline');
var FileSystem = require('fs');
var Readline = require('readline');
var Utilities = require('util');

var countOfTasks = 0;
var countOfProcessed = 0;

var output = Readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

output.setPrompt('');
output.write(Utilities.format('tasks:%d processed:%d ', countOfTasks, countOfProcessed));

var interval = setInterval(function() {

  output.write(null, {
    ctrl: true,
    name: 'u'
  });

  output.write(Utilities.format('tasks:%d processed:%d ', countOfTasks, countOfProcessed));

}, 250)

Asynchronous.waterfall([
  function(callback) {

    var queue = Asynchronous.queue(function(task, callback) {

      FileSystem.appendFileSync('debug-processing-preTimeout', Utilities.format('%s\n', task.line));

      setTimeout(function() {
        FileSystem.appendFileSync('debug-processing-inTimeout', Utilities.format('%s\n', task.line));
        callback();
      }, 0);

    }, 1);

    // queue.drain = function() {
    //   callback();
    // };

    var lines = ByLine.createStream(FileSystem.createReadStream('lines'));

    lines
      .on('data', function(line) {

        countOfTasks ++;

        var task = {
          line: line
        };

        FileSystem.appendFileSync('debug-pushing', Utilities.format('%s\n', line));

        queue.push(task, function(error) {

          FileSystem.appendFileSync('debug-processed', Utilities.format('%s\n', line));

          countOfProcessed ++;
          countOfTasks --;

          if (countOfTasks == 0)
            lines.resume();

        });

        if (countOfTasks >= 5)
          lines.pause();

      })
      .on('error', callback);

  }
], function(error) {

  clearInterval(interval);

  if (error) {

    output.write(null, {
      ctrl: true,
      name: 'u'
    });

    output.write(Utilities.format('Error ... %s\n\n', error.message));

  }

  output.write(null, {
    ctrl: true,
    name: 'u'
  });

  output.write(Utilities.format('Done ... processed:%d\n\n', countOfProcessed));
  output.close();

});
```

Notice that the size of the input file (lines) is different from the size of an output file (e.g. debug-pushed).  It seems as if lines are missing from the end.

**Comment by jahewson** [comment]
> It seems as if lines are missing from the end.

Are there lines missing from the end or not? By default empty lines will be stripped, so if you have any then the counts won't match.

**Comment by virtualpatterns** [comment]
The missing lines are at the end.  There are no blank lines in my test file.

**Comment by beppu** [comment]
FWIW, I think I'm running into the same bug.  In my case, it inexplicably but predictably stops at 16426 lines when trying to process a 30000 line file.

**Comment by jahewson** [comment]
Ok, thanks. I'll take a closer look at this issue today.

**Comment by jahewson** [comment]
I managed to reproduce this problem. It occurs when using pause() and resume() on files with over 16384 lines. That number is special, it's the [highWaterMark](https://github.com/joyent/node/blob/master/lib/_stream_readable.js#L47) of stream.Readable, which is it's internal output buffer.

When the (output) readable stream's buffer is full, `readable.push(chunk)` returns false. Byline handled this by buffering up the lines internally and finally writing them when flush() is called on the stream. However, flush() also calls `readable.push(chunk)`, which returns false when there are over 16384 lines in the output stream's buffer, which can happen if pause() has been called. In this situation, byline never retried the push, and any subsequent data was lost.

The solution is to retry the push asynchronously on the next tick, rather than buffering up a large number of lines within LineStream's buffer and trying to flush it all at the end. Both _transform and _flush can benefit from this approach.

Thanks for reporting this bug! Please try out the latest master, and if it works for you then I will do a release on npm.

**Comment by jahewson** [comment]
As an aside: it should be noted that since streams2 was introduced in v0.10, pause() and resume() are considered to be obsolete. Back pressure is now managed by consumers, rather than producers, in fact, pause() and resume() cause a performance degradation.

Instead of using pause(), resume(), and on('data'), call [stream.read()](http://nodejs.org/api/stream.html#stream_readable_read_size) to use the stream in _non-flowing mode_. See the link for an example. There's no need to specify the `size` parameter, because byline uses _object mode_.

**Comment by virtualpatterns** [comment]
The latest master branch has fixed the issue.

**Comment by jahewson** [comment]
Great, I'll do a release on npm soon.
