### ISSUE TITLE
Undoing byline(streamX)

### ISSUE THREAD

**Issue by cefn** [jahewson/node-byline#42]
It's not clear how to dispose of streams created by the byline wrapper invocation, like the following to wrap bytestreams coming out of an invoked shell...

```
var outStream = byline(shell.stdout);
var errStream = byline(shell.stderr);
```

Currently there is a point in my program where my on 'data' handler is unsubscribed and I was expecting to be able to dispose of the line-oriented wrapper at that point, but can't find a destroy() method or anything equivalent.

**Comment by jahewson** [comment]
I don't understand your example because you're trying to wrap writable streams, but byline is for wrapping readable streams.

I'm going to assume you're actually trying to do something like:

``` js
var inStream = byline(shell.stdin);
```

In which case you have two choices. Either use LineStream directly instead of using the byline convenience function, or unpipe the original stream:

``` js
shell.stdin.unpipe(inStream);
```

**Comment by cefn** [comment]
The original case was indeed a readable stream - a stream representing the bytes written to stdout by a program invoked in a shell (shell is the result of child_process.spawn with options containing shell:true). 

I should have provided more context. The example you've provided sounds exactly what I need.
